### PR TITLE
Merging develop into master for new release

### PR DESCRIPTION
**Pull request by christophertull**

### CODE REVIEW

**Comment by patwater** [comment]
Wow looks like a lots going on!  All good? @christophertull @anudeepvanjavakam1 ?

**Comment by anudeepvanjavakam1** [comment]
@patwater Yeah. Everything is coming along nicely. I am working on unit tests now. Once completed, this merge is good to go!

**Comment by christophertull** [comment]
Yeah this is just to move all of the changes for the last 3 months (which have been in the `develop` branch) into the `master` branch. Call it our version 0.3.0 release 🚢

**Comment by patwater** [comment]
Cool!  Perhaps we should consider officially versioning RC to v2?  CCing @vr00n for best practice thoughts on versioning software development :)

**Comment by christophertull** [comment]
I was thinking version 1.0 (currently in the 0.x). Although me being me,
there are always a couple more changes I wanna see before versioning up ;)

**Comment by patwater** [comment]
Sounds good though note I've been referring to the Stanford presentation as v1 and this with expansion to customer class and forecasting as v2.  Also what changes explicitly?

**Comment by christophertull** [comment]
New things since LVMWD last saw the tool

Multiple customer classes
Each class has its own controls and own rate structure
Service charge varies by meter size
Forecasting N months into the future
Account growth / decline
Price elasticity and demand response
Data export
OWRS file

**Pull request merged**
