### PR TITLE
Integrate RateParser

### LINKED ISSUE #10: Calculate bills using a machine-readable rate format
Currently, in order to calculate the "baseline" bills, a rate structure must be hard-coded into the source of the tool. It would be much better if the pricing structure could be read from a text file that fully specified the structure and any data dependencies.

Most likely, this will take the form of a function `calculate_bill()` that could do something like the following:

`total_bills <- calculate_bill( data, rate_schedule_string )`

Before this can happen, a format for storing and transmitting rates needs to be devised, which is a problem that I a working on, probably in a different repo.

### LINKED ISSUE #12: Load rate structure from a file
Users should be able to load a rate structure from a file, either to set the baseline rates or to populate the boxes in the customer class tabs. There should probably be an import button somewhere.

Before this can happen, a format for storing and transmitting rates needs to be devised, which is a problem that I a working on, probably in a different repo.

### LINKED ISSUE #18: Change fixed charge based on meter size
The fixed charge should change based on the meter size of the account. There should be new input boxes on the left that allow the user to specify the charge for each meter size.

### LINKED ISSUE #21: Refactor UI and Server files into Modules
Right now the different UI tabs and charts are all copy-pasted and suffixed with numbers (e.g. df_plots1, df_plots2, etc). This is fine for the short term, but it will make the code more readable, and maintainable if we refactor these into Shiny Modules and then generate them in a loop.

See here for info on creating modules: http://shiny.rstudio.com/articles/modules.html

And here for generating a UI in a loop: http://shiny.rstudio.com/gallery/creating-a-ui-from-a-loop.html

### PR DESCRIPTION
**Pull request by christophertull**
All of the water rate calculations are now being done using RateParser! There are still a couple of minor changes to make and bugs to squash, but most everything is working now. 

New features include:
- baseline rates are calculated using RP
- hypothetical rates are parsed from the inputs into a nested list and then calculated using RP
- Each customer class has their own set of inputs
- some fields can depend on other fields. for example service charge can depend on meter size, or landscaep factor can depend on water supply type
- Scenario planning is moved up to the navbar
- Most of the code that was copy-pasted has been refactored either into functions or into modules:
  - class_graphs.R
  - rate_inputs.R

This PR closes #21, closes #12, closes #18, closes #10

### CODE REVIEW

**Comment by christophertull** [comment]
Sorry for taking a while and making such a big monolithic change! In the future I will try to keep the changes smaller and easily digestible.

**Comment by monobina** [comment]
@christophertull which repo should I clone for testing? the rate comparison or the rate parser ?

**Comment by monobina** [comment]
i think i should clone the owrsfinal branch..right?

**Comment by christophertull** [comment]
Just FYI if you guys are looking to test locally,

1. pull down the OWRSupdatesfinal branch
   - `git checkout --track origin/OWRSupdatesfinal`
2. download the latest MNWD OWRS file
   - https://raw.githubusercontent.com/California-Data-Collaborative/Open-Water-Rate-Specification/master/examples/mnwd.owrs
3. install the latest `RateParser`
 ```r
#might need to uninstall first?
 #remove.packages("RateParser")
 devtools::install_github("California-Data-Collaborative/RateParser")
```

Then you should be good to go. Or ask here if something comes up.

**Comment by monobina** [comment]
@christophertull i think i was able to succesfully check out the oWRSupdatesfinal. I also copied the owrs file from link you sent into the folder. I am tetsing it with our mnwd_test dataset aand had toc hange some path to directory to make it consistent to where the files are saved. After fixing all of the above I am getting an error saying Error in seq_len(max) : 
  argument must be coercible to non-negative integer

any clue on this? anything to do with the min max on the usage_date in global?

**Comment by monobina** [comment]
@christophertull the code is able to read the df and stops running. The usage_date values does not look like a date after the code reads in the dataframe. Is the as.date function doing something?

**Comment by monobina** [comment]
the dataframe reading issue is resolved :-)  it had to do with the format of date in the spreadsheet

**Comment by christophertull** [comment]
Merging this into develop since no issues.

**Pull request merged**
